// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// InsertUserKeyValueReader is a Reader for the InsertUserKeyValue structure.
type InsertUserKeyValueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InsertUserKeyValueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewInsertUserKeyValueCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewInsertUserKeyValueBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInsertUserKeyValueCreated creates a InsertUserKeyValueCreated with default headers values
func NewInsertUserKeyValueCreated() *InsertUserKeyValueCreated {
	return &InsertUserKeyValueCreated{}
}

/* InsertUserKeyValueCreated describes a response with status code 201, with default header values.

Per tenant config uploaded successfully
*/
type InsertUserKeyValueCreated struct {
	Payload *kbmodel.TenantKeyValue
}

func (o *InsertUserKeyValueCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/tenants/userKeyValue/{keyName}][%d] insertUserKeyValueCreated  %+v", 201, o.Payload)
}
func (o *InsertUserKeyValueCreated) GetPayload() *kbmodel.TenantKeyValue {
	return o.Payload
}

func (o *InsertUserKeyValueCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.TenantKeyValue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInsertUserKeyValueBadRequest creates a InsertUserKeyValueBadRequest with default headers values
func NewInsertUserKeyValueBadRequest() *InsertUserKeyValueBadRequest {
	return &InsertUserKeyValueBadRequest{}
}

/* InsertUserKeyValueBadRequest describes a response with status code 400, with default header values.

Invalid tenantId supplied
*/
type InsertUserKeyValueBadRequest struct {
}

func (o *InsertUserKeyValueBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/tenants/userKeyValue/{keyName}][%d] insertUserKeyValueBadRequest ", 400)
}

func (o *InsertUserKeyValueBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
