// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// UploadPerTenantConfigurationReader is a Reader for the UploadPerTenantConfiguration structure.
type UploadPerTenantConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadPerTenantConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUploadPerTenantConfigurationCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUploadPerTenantConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUploadPerTenantConfigurationCreated creates a UploadPerTenantConfigurationCreated with default headers values
func NewUploadPerTenantConfigurationCreated() *UploadPerTenantConfigurationCreated {
	return &UploadPerTenantConfigurationCreated{}
}

/* UploadPerTenantConfigurationCreated describes a response with status code 201, with default header values.

Per tenant configuration uploaded successfully
*/
type UploadPerTenantConfigurationCreated struct {
	Payload *kbmodel.TenantKeyValue
}

func (o *UploadPerTenantConfigurationCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/tenants/uploadPerTenantConfig][%d] uploadPerTenantConfigurationCreated  %+v", 201, o.Payload)
}
func (o *UploadPerTenantConfigurationCreated) GetPayload() *kbmodel.TenantKeyValue {
	return o.Payload
}

func (o *UploadPerTenantConfigurationCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.TenantKeyValue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadPerTenantConfigurationBadRequest creates a UploadPerTenantConfigurationBadRequest with default headers values
func NewUploadPerTenantConfigurationBadRequest() *UploadPerTenantConfigurationBadRequest {
	return &UploadPerTenantConfigurationBadRequest{}
}

/* UploadPerTenantConfigurationBadRequest describes a response with status code 400, with default header values.

Invalid tenantId supplied
*/
type UploadPerTenantConfigurationBadRequest struct {
}

func (o *UploadPerTenantConfigurationBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/tenants/uploadPerTenantConfig][%d] uploadPerTenantConfigurationBadRequest ", 400)
}

func (o *UploadPerTenantConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
