// Code generated by go-swagger; DO NOT EDIT.

package overdue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOverdueConfigXMLReader is a Reader for the GetOverdueConfigXML structure.
type GetOverdueConfigXMLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOverdueConfigXMLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOverdueConfigXMLOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOverdueConfigXMLOK creates a GetOverdueConfigXMLOK with default headers values
func NewGetOverdueConfigXMLOK() *GetOverdueConfigXMLOK {
	return &GetOverdueConfigXMLOK{}
}

/* GetOverdueConfigXMLOK describes a response with status code 200, with default header values.

successful operation
*/
type GetOverdueConfigXMLOK struct {
	Payload string
}

func (o *GetOverdueConfigXMLOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/overdue/xml][%d] getOverdueConfigXmlOK  %+v", 200, o.Payload)
}
func (o *GetOverdueConfigXMLOK) GetPayload() string {
	return o.Payload
}

func (o *GetOverdueConfigXMLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
