// Code generated by go-swagger; DO NOT EDIT.

package credit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// CreateCreditsReader is a Reader for the CreateCredits structure.
type CreateCreditsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCreditsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateCreditsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCreditsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateCreditsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCreditsCreated creates a CreateCreditsCreated with default headers values
func NewCreateCreditsCreated() *CreateCreditsCreated {
	return &CreateCreditsCreated{}
}

/* CreateCreditsCreated describes a response with status code 201, with default header values.

Created credit successfully
*/
type CreateCreditsCreated struct {
	Payload []*kbmodel.InvoiceItem
}

func (o *CreateCreditsCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/credits][%d] createCreditsCreated  %+v", 201, o.Payload)
}
func (o *CreateCreditsCreated) GetPayload() []*kbmodel.InvoiceItem {
	return o.Payload
}

func (o *CreateCreditsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCreditsBadRequest creates a CreateCreditsBadRequest with default headers values
func NewCreateCreditsBadRequest() *CreateCreditsBadRequest {
	return &CreateCreditsBadRequest{}
}

/* CreateCreditsBadRequest describes a response with status code 400, with default header values.

Invalid account id supplied
*/
type CreateCreditsBadRequest struct {
}

func (o *CreateCreditsBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/credits][%d] createCreditsBadRequest ", 400)
}

func (o *CreateCreditsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateCreditsNotFound creates a CreateCreditsNotFound with default headers values
func NewCreateCreditsNotFound() *CreateCreditsNotFound {
	return &CreateCreditsNotFound{}
}

/* CreateCreditsNotFound describes a response with status code 404, with default header values.

Account not found
*/
type CreateCreditsNotFound struct {
}

func (o *CreateCreditsNotFound) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/credits][%d] createCreditsNotFound ", 404)
}

func (o *CreateCreditsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
