// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// CreatePaymentMethodReader is a Reader for the CreatePaymentMethod structure.
type CreatePaymentMethodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePaymentMethodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreatePaymentMethodCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreatePaymentMethodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreatePaymentMethodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreatePaymentMethodCreated creates a CreatePaymentMethodCreated with default headers values
func NewCreatePaymentMethodCreated() *CreatePaymentMethodCreated {
	return &CreatePaymentMethodCreated{}
}

/* CreatePaymentMethodCreated describes a response with status code 201, with default header values.

Payment method created
*/
type CreatePaymentMethodCreated struct {
	Payload *kbmodel.PaymentMethod
}

func (o *CreatePaymentMethodCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/accounts/{accountId}/paymentMethods][%d] createPaymentMethodCreated  %+v", 201, o.Payload)
}
func (o *CreatePaymentMethodCreated) GetPayload() *kbmodel.PaymentMethod {
	return o.Payload
}

func (o *CreatePaymentMethodCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.PaymentMethod)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePaymentMethodBadRequest creates a CreatePaymentMethodBadRequest with default headers values
func NewCreatePaymentMethodBadRequest() *CreatePaymentMethodBadRequest {
	return &CreatePaymentMethodBadRequest{}
}

/* CreatePaymentMethodBadRequest describes a response with status code 400, with default header values.

Invalid account id supplied
*/
type CreatePaymentMethodBadRequest struct {
}

func (o *CreatePaymentMethodBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/accounts/{accountId}/paymentMethods][%d] createPaymentMethodBadRequest ", 400)
}

func (o *CreatePaymentMethodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePaymentMethodNotFound creates a CreatePaymentMethodNotFound with default headers values
func NewCreatePaymentMethodNotFound() *CreatePaymentMethodNotFound {
	return &CreatePaymentMethodNotFound{}
}

/* CreatePaymentMethodNotFound describes a response with status code 404, with default header values.

Account not found
*/
type CreatePaymentMethodNotFound struct {
}

func (o *CreatePaymentMethodNotFound) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/accounts/{accountId}/paymentMethods][%d] createPaymentMethodNotFound ", 404)
}

func (o *CreatePaymentMethodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
