// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// GetAllCustomFieldsReader is a Reader for the GetAllCustomFields structure.
type GetAllCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllCustomFieldsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAllCustomFieldsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAllCustomFieldsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllCustomFieldsOK creates a GetAllCustomFieldsOK with default headers values
func NewGetAllCustomFieldsOK() *GetAllCustomFieldsOK {
	return &GetAllCustomFieldsOK{}
}

/* GetAllCustomFieldsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllCustomFieldsOK struct {
	Payload []*kbmodel.CustomField
}

func (o *GetAllCustomFieldsOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/accounts/{accountId}/allCustomFields][%d] getAllCustomFieldsOK  %+v", 200, o.Payload)
}
func (o *GetAllCustomFieldsOK) GetPayload() []*kbmodel.CustomField {
	return o.Payload
}

func (o *GetAllCustomFieldsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllCustomFieldsBadRequest creates a GetAllCustomFieldsBadRequest with default headers values
func NewGetAllCustomFieldsBadRequest() *GetAllCustomFieldsBadRequest {
	return &GetAllCustomFieldsBadRequest{}
}

/* GetAllCustomFieldsBadRequest describes a response with status code 400, with default header values.

Invalid account id supplied
*/
type GetAllCustomFieldsBadRequest struct {
}

func (o *GetAllCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/accounts/{accountId}/allCustomFields][%d] getAllCustomFieldsBadRequest ", 400)
}

func (o *GetAllCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllCustomFieldsNotFound creates a GetAllCustomFieldsNotFound with default headers values
func NewGetAllCustomFieldsNotFound() *GetAllCustomFieldsNotFound {
	return &GetAllCustomFieldsNotFound{}
}

/* GetAllCustomFieldsNotFound describes a response with status code 404, with default header values.

Account not found
*/
type GetAllCustomFieldsNotFound struct {
}

func (o *GetAllCustomFieldsNotFound) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/accounts/{accountId}/allCustomFields][%d] getAllCustomFieldsNotFound ", 404)
}

func (o *GetAllCustomFieldsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
