// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/killbill/kbcli/v2/kbmodel"
)

// PayAllInvoicesReader is a Reader for the PayAllInvoices structure.
type PayAllInvoicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PayAllInvoicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPayAllInvoicesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewPayAllInvoicesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPayAllInvoicesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPayAllInvoicesCreated creates a PayAllInvoicesCreated with default headers values
func NewPayAllInvoicesCreated() *PayAllInvoicesCreated {
	return &PayAllInvoicesCreated{}
}

/* PayAllInvoicesCreated describes a response with status code 201, with default header values.

Successful operation
*/
type PayAllInvoicesCreated struct {
	Payload []*kbmodel.Invoice
}

func (o *PayAllInvoicesCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/accounts/{accountId}/invoicePayments][%d] payAllInvoicesCreated  %+v", 201, o.Payload)
}
func (o *PayAllInvoicesCreated) GetPayload() []*kbmodel.Invoice {
	return o.Payload
}

func (o *PayAllInvoicesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPayAllInvoicesNoContent creates a PayAllInvoicesNoContent with default headers values
func NewPayAllInvoicesNoContent() *PayAllInvoicesNoContent {
	return &PayAllInvoicesNoContent{}
}

/* PayAllInvoicesNoContent describes a response with status code 204, with default header values.

Nothing to pay
*/
type PayAllInvoicesNoContent struct {
}

func (o *PayAllInvoicesNoContent) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/accounts/{accountId}/invoicePayments][%d] payAllInvoicesNoContent ", 204)
}

func (o *PayAllInvoicesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPayAllInvoicesNotFound creates a PayAllInvoicesNotFound with default headers values
func NewPayAllInvoicesNotFound() *PayAllInvoicesNotFound {
	return &PayAllInvoicesNotFound{}
}

/* PayAllInvoicesNotFound describes a response with status code 404, with default header values.

Invalid account id supplied
*/
type PayAllInvoicesNotFound struct {
}

func (o *PayAllInvoicesNotFound) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/accounts/{accountId}/invoicePayments][%d] payAllInvoicesNotFound ", 404)
}

func (o *PayAllInvoicesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
