// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RefreshPaymentMethodsReader is a Reader for the RefreshPaymentMethods structure.
type RefreshPaymentMethodsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RefreshPaymentMethodsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRefreshPaymentMethodsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRefreshPaymentMethodsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRefreshPaymentMethodsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRefreshPaymentMethodsNoContent creates a RefreshPaymentMethodsNoContent with default headers values
func NewRefreshPaymentMethodsNoContent() *RefreshPaymentMethodsNoContent {
	return &RefreshPaymentMethodsNoContent{}
}

/* RefreshPaymentMethodsNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type RefreshPaymentMethodsNoContent struct {
}

func (o *RefreshPaymentMethodsNoContent) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/accounts/{accountId}/paymentMethods/refresh][%d] refreshPaymentMethodsNoContent ", 204)
}

func (o *RefreshPaymentMethodsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRefreshPaymentMethodsBadRequest creates a RefreshPaymentMethodsBadRequest with default headers values
func NewRefreshPaymentMethodsBadRequest() *RefreshPaymentMethodsBadRequest {
	return &RefreshPaymentMethodsBadRequest{}
}

/* RefreshPaymentMethodsBadRequest describes a response with status code 400, with default header values.

Invalid account id supplied
*/
type RefreshPaymentMethodsBadRequest struct {
}

func (o *RefreshPaymentMethodsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/accounts/{accountId}/paymentMethods/refresh][%d] refreshPaymentMethodsBadRequest ", 400)
}

func (o *RefreshPaymentMethodsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRefreshPaymentMethodsNotFound creates a RefreshPaymentMethodsNotFound with default headers values
func NewRefreshPaymentMethodsNotFound() *RefreshPaymentMethodsNotFound {
	return &RefreshPaymentMethodsNotFound{}
}

/* RefreshPaymentMethodsNotFound describes a response with status code 404, with default header values.

Account not found
*/
type RefreshPaymentMethodsNotFound struct {
}

func (o *RefreshPaymentMethodsNotFound) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/accounts/{accountId}/paymentMethods/refresh][%d] refreshPaymentMethodsNotFound ", 404)
}

func (o *RefreshPaymentMethodsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
