// Code generated by go-swagger; DO NOT EDIT.

package payment_method

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeletePaymentMethodReader is a Reader for the DeletePaymentMethod structure.
type DeletePaymentMethodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePaymentMethodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePaymentMethodNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeletePaymentMethodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeletePaymentMethodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeletePaymentMethodNoContent creates a DeletePaymentMethodNoContent with default headers values
func NewDeletePaymentMethodNoContent() *DeletePaymentMethodNoContent {
	return &DeletePaymentMethodNoContent{}
}

/* DeletePaymentMethodNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeletePaymentMethodNoContent struct {
}

func (o *DeletePaymentMethodNoContent) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/paymentMethods/{paymentMethodId}][%d] deletePaymentMethodNoContent ", 204)
}

func (o *DeletePaymentMethodNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePaymentMethodBadRequest creates a DeletePaymentMethodBadRequest with default headers values
func NewDeletePaymentMethodBadRequest() *DeletePaymentMethodBadRequest {
	return &DeletePaymentMethodBadRequest{}
}

/* DeletePaymentMethodBadRequest describes a response with status code 400, with default header values.

Invalid paymentMethodId supplied
*/
type DeletePaymentMethodBadRequest struct {
}

func (o *DeletePaymentMethodBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/paymentMethods/{paymentMethodId}][%d] deletePaymentMethodBadRequest ", 400)
}

func (o *DeletePaymentMethodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePaymentMethodNotFound creates a DeletePaymentMethodNotFound with default headers values
func NewDeletePaymentMethodNotFound() *DeletePaymentMethodNotFound {
	return &DeletePaymentMethodNotFound{}
}

/* DeletePaymentMethodNotFound describes a response with status code 404, with default header values.

Account or payment method not found
*/
type DeletePaymentMethodNotFound struct {
}

func (o *DeletePaymentMethodNotFound) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/paymentMethods/{paymentMethodId}][%d] deletePaymentMethodNotFound ", 404)
}

func (o *DeletePaymentMethodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
