// Code generated by go-swagger; DO NOT EDIT.

package usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// GetAllUsageReader is a Reader for the GetAllUsage structure.
type GetAllUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAllUsageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllUsageOK creates a GetAllUsageOK with default headers values
func NewGetAllUsageOK() *GetAllUsageOK {
	return &GetAllUsageOK{}
}

/* GetAllUsageOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllUsageOK struct {
	Payload *kbmodel.RolledUpUsage
}

func (o *GetAllUsageOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/usages/{subscriptionId}][%d] getAllUsageOK  %+v", 200, o.Payload)
}
func (o *GetAllUsageOK) GetPayload() *kbmodel.RolledUpUsage {
	return o.Payload
}

func (o *GetAllUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.RolledUpUsage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllUsageBadRequest creates a GetAllUsageBadRequest with default headers values
func NewGetAllUsageBadRequest() *GetAllUsageBadRequest {
	return &GetAllUsageBadRequest{}
}

/* GetAllUsageBadRequest describes a response with status code 400, with default header values.

Missing start date or end date
*/
type GetAllUsageBadRequest struct {
}

func (o *GetAllUsageBadRequest) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/usages/{subscriptionId}][%d] getAllUsageBadRequest ", 400)
}

func (o *GetAllUsageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
