// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CancelSubscriptionPlanReader is a Reader for the CancelSubscriptionPlan structure.
type CancelSubscriptionPlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelSubscriptionPlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCancelSubscriptionPlanNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCancelSubscriptionPlanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCancelSubscriptionPlanNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCancelSubscriptionPlanNoContent creates a CancelSubscriptionPlanNoContent with default headers values
func NewCancelSubscriptionPlanNoContent() *CancelSubscriptionPlanNoContent {
	return &CancelSubscriptionPlanNoContent{}
}

/* CancelSubscriptionPlanNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type CancelSubscriptionPlanNoContent struct {
}

func (o *CancelSubscriptionPlanNoContent) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/subscriptions/{subscriptionId}][%d] cancelSubscriptionPlanNoContent ", 204)
}

func (o *CancelSubscriptionPlanNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCancelSubscriptionPlanBadRequest creates a CancelSubscriptionPlanBadRequest with default headers values
func NewCancelSubscriptionPlanBadRequest() *CancelSubscriptionPlanBadRequest {
	return &CancelSubscriptionPlanBadRequest{}
}

/* CancelSubscriptionPlanBadRequest describes a response with status code 400, with default header values.

Invalid subscription id supplied
*/
type CancelSubscriptionPlanBadRequest struct {
}

func (o *CancelSubscriptionPlanBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/subscriptions/{subscriptionId}][%d] cancelSubscriptionPlanBadRequest ", 400)
}

func (o *CancelSubscriptionPlanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCancelSubscriptionPlanNotFound creates a CancelSubscriptionPlanNotFound with default headers values
func NewCancelSubscriptionPlanNotFound() *CancelSubscriptionPlanNotFound {
	return &CancelSubscriptionPlanNotFound{}
}

/* CancelSubscriptionPlanNotFound describes a response with status code 404, with default header values.

Entitlement not found
*/
type CancelSubscriptionPlanNotFound struct {
}

func (o *CancelSubscriptionPlanNotFound) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/subscriptions/{subscriptionId}][%d] cancelSubscriptionPlanNotFound ", 404)
}

func (o *CancelSubscriptionPlanNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
