// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteSubscriptionCustomFieldsReader is a Reader for the DeleteSubscriptionCustomFields structure.
type DeleteSubscriptionCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubscriptionCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSubscriptionCustomFieldsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSubscriptionCustomFieldsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSubscriptionCustomFieldsNoContent creates a DeleteSubscriptionCustomFieldsNoContent with default headers values
func NewDeleteSubscriptionCustomFieldsNoContent() *DeleteSubscriptionCustomFieldsNoContent {
	return &DeleteSubscriptionCustomFieldsNoContent{}
}

/* DeleteSubscriptionCustomFieldsNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeleteSubscriptionCustomFieldsNoContent struct {
}

func (o *DeleteSubscriptionCustomFieldsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/subscriptions/{subscriptionId}/customFields][%d] deleteSubscriptionCustomFieldsNoContent ", 204)
}

func (o *DeleteSubscriptionCustomFieldsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubscriptionCustomFieldsBadRequest creates a DeleteSubscriptionCustomFieldsBadRequest with default headers values
func NewDeleteSubscriptionCustomFieldsBadRequest() *DeleteSubscriptionCustomFieldsBadRequest {
	return &DeleteSubscriptionCustomFieldsBadRequest{}
}

/* DeleteSubscriptionCustomFieldsBadRequest describes a response with status code 400, with default header values.

Invalid subscription id supplied
*/
type DeleteSubscriptionCustomFieldsBadRequest struct {
}

func (o *DeleteSubscriptionCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/subscriptions/{subscriptionId}/customFields][%d] deleteSubscriptionCustomFieldsBadRequest ", 400)
}

func (o *DeleteSubscriptionCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
