// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// GetSubscriptionEventAuditLogsWithHistoryReader is a Reader for the GetSubscriptionEventAuditLogsWithHistory structure.
type GetSubscriptionEventAuditLogsWithHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubscriptionEventAuditLogsWithHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSubscriptionEventAuditLogsWithHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetSubscriptionEventAuditLogsWithHistoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSubscriptionEventAuditLogsWithHistoryOK creates a GetSubscriptionEventAuditLogsWithHistoryOK with default headers values
func NewGetSubscriptionEventAuditLogsWithHistoryOK() *GetSubscriptionEventAuditLogsWithHistoryOK {
	return &GetSubscriptionEventAuditLogsWithHistoryOK{}
}

/* GetSubscriptionEventAuditLogsWithHistoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetSubscriptionEventAuditLogsWithHistoryOK struct {
	Payload []*kbmodel.AuditLog
}

func (o *GetSubscriptionEventAuditLogsWithHistoryOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/subscriptions/events/{eventId}/auditLogsWithHistory][%d] getSubscriptionEventAuditLogsWithHistoryOK  %+v", 200, o.Payload)
}
func (o *GetSubscriptionEventAuditLogsWithHistoryOK) GetPayload() []*kbmodel.AuditLog {
	return o.Payload
}

func (o *GetSubscriptionEventAuditLogsWithHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSubscriptionEventAuditLogsWithHistoryNotFound creates a GetSubscriptionEventAuditLogsWithHistoryNotFound with default headers values
func NewGetSubscriptionEventAuditLogsWithHistoryNotFound() *GetSubscriptionEventAuditLogsWithHistoryNotFound {
	return &GetSubscriptionEventAuditLogsWithHistoryNotFound{}
}

/* GetSubscriptionEventAuditLogsWithHistoryNotFound describes a response with status code 404, with default header values.

Subscription event not found
*/
type GetSubscriptionEventAuditLogsWithHistoryNotFound struct {
}

func (o *GetSubscriptionEventAuditLogsWithHistoryNotFound) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/subscriptions/events/{eventId}/auditLogsWithHistory][%d] getSubscriptionEventAuditLogsWithHistoryNotFound ", 404)
}

func (o *GetSubscriptionEventAuditLogsWithHistoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
