// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UncancelSubscriptionPlanReader is a Reader for the UncancelSubscriptionPlan structure.
type UncancelSubscriptionPlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UncancelSubscriptionPlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUncancelSubscriptionPlanNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUncancelSubscriptionPlanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUncancelSubscriptionPlanNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUncancelSubscriptionPlanNoContent creates a UncancelSubscriptionPlanNoContent with default headers values
func NewUncancelSubscriptionPlanNoContent() *UncancelSubscriptionPlanNoContent {
	return &UncancelSubscriptionPlanNoContent{}
}

/* UncancelSubscriptionPlanNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type UncancelSubscriptionPlanNoContent struct {
}

func (o *UncancelSubscriptionPlanNoContent) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/subscriptions/{subscriptionId}/uncancel][%d] uncancelSubscriptionPlanNoContent ", 204)
}

func (o *UncancelSubscriptionPlanNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUncancelSubscriptionPlanBadRequest creates a UncancelSubscriptionPlanBadRequest with default headers values
func NewUncancelSubscriptionPlanBadRequest() *UncancelSubscriptionPlanBadRequest {
	return &UncancelSubscriptionPlanBadRequest{}
}

/* UncancelSubscriptionPlanBadRequest describes a response with status code 400, with default header values.

Invalid subscription id supplied
*/
type UncancelSubscriptionPlanBadRequest struct {
}

func (o *UncancelSubscriptionPlanBadRequest) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/subscriptions/{subscriptionId}/uncancel][%d] uncancelSubscriptionPlanBadRequest ", 400)
}

func (o *UncancelSubscriptionPlanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUncancelSubscriptionPlanNotFound creates a UncancelSubscriptionPlanNotFound with default headers values
func NewUncancelSubscriptionPlanNotFound() *UncancelSubscriptionPlanNotFound {
	return &UncancelSubscriptionPlanNotFound{}
}

/* UncancelSubscriptionPlanNotFound describes a response with status code 404, with default header values.

Entitlement not found
*/
type UncancelSubscriptionPlanNotFound struct {
}

func (o *UncancelSubscriptionPlanNotFound) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/subscriptions/{subscriptionId}/uncancel][%d] uncancelSubscriptionPlanNotFound ", 404)
}

func (o *UncancelSubscriptionPlanNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
