// Code generated by go-swagger; DO NOT EDIT.

package invoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/killbill/kbcli/v2/kbmodel"
)

// CreateInstantPaymentReader is a Reader for the CreateInstantPayment structure.
type CreateInstantPaymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInstantPaymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateInstantPaymentCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewCreateInstantPaymentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateInstantPaymentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateInstantPaymentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateInstantPaymentCreated creates a CreateInstantPaymentCreated with default headers values
func NewCreateInstantPaymentCreated() *CreateInstantPaymentCreated {
	return &CreateInstantPaymentCreated{}
}

/* CreateInstantPaymentCreated describes a response with status code 201, with default header values.

Created payment Successfully
*/
type CreateInstantPaymentCreated struct {
	Payload *kbmodel.InvoicePayment
}

func (o *CreateInstantPaymentCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoices/{invoiceId}/payments][%d] createInstantPaymentCreated  %+v", 201, o.Payload)
}
func (o *CreateInstantPaymentCreated) GetPayload() *kbmodel.InvoicePayment {
	return o.Payload
}

func (o *CreateInstantPaymentCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.InvoicePayment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateInstantPaymentNoContent creates a CreateInstantPaymentNoContent with default headers values
func NewCreateInstantPaymentNoContent() *CreateInstantPaymentNoContent {
	return &CreateInstantPaymentNoContent{}
}

/* CreateInstantPaymentNoContent describes a response with status code 204, with default header values.

Nothing to pay for
*/
type CreateInstantPaymentNoContent struct {
}

func (o *CreateInstantPaymentNoContent) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoices/{invoiceId}/payments][%d] createInstantPaymentNoContent ", 204)
}

func (o *CreateInstantPaymentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstantPaymentBadRequest creates a CreateInstantPaymentBadRequest with default headers values
func NewCreateInstantPaymentBadRequest() *CreateInstantPaymentBadRequest {
	return &CreateInstantPaymentBadRequest{}
}

/* CreateInstantPaymentBadRequest describes a response with status code 400, with default header values.

Invalid account id or invoice id supplied
*/
type CreateInstantPaymentBadRequest struct {
}

func (o *CreateInstantPaymentBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoices/{invoiceId}/payments][%d] createInstantPaymentBadRequest ", 400)
}

func (o *CreateInstantPaymentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstantPaymentNotFound creates a CreateInstantPaymentNotFound with default headers values
func NewCreateInstantPaymentNotFound() *CreateInstantPaymentNotFound {
	return &CreateInstantPaymentNotFound{}
}

/* CreateInstantPaymentNotFound describes a response with status code 404, with default header values.

Account not found
*/
type CreateInstantPaymentNotFound struct {
}

func (o *CreateInstantPaymentNotFound) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoices/{invoiceId}/payments][%d] createInstantPaymentNotFound ", 404)
}

func (o *CreateInstantPaymentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
