// Code generated by go-swagger; DO NOT EDIT.

package invoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// GetInvoiceByItemIDReader is a Reader for the GetInvoiceByItemID structure.
type GetInvoiceByItemIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInvoiceByItemIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInvoiceByItemIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetInvoiceByItemIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetInvoiceByItemIDOK creates a GetInvoiceByItemIDOK with default headers values
func NewGetInvoiceByItemIDOK() *GetInvoiceByItemIDOK {
	return &GetInvoiceByItemIDOK{}
}

/* GetInvoiceByItemIDOK describes a response with status code 200, with default header values.

successful operation
*/
type GetInvoiceByItemIDOK struct {
	Payload *kbmodel.Invoice
}

func (o *GetInvoiceByItemIDOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/invoices/byItemId/{itemId}][%d] getInvoiceByItemIdOK  %+v", 200, o.Payload)
}
func (o *GetInvoiceByItemIDOK) GetPayload() *kbmodel.Invoice {
	return o.Payload
}

func (o *GetInvoiceByItemIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.Invoice)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoiceByItemIDNotFound creates a GetInvoiceByItemIDNotFound with default headers values
func NewGetInvoiceByItemIDNotFound() *GetInvoiceByItemIDNotFound {
	return &GetInvoiceByItemIDNotFound{}
}

/* GetInvoiceByItemIDNotFound describes a response with status code 404, with default header values.

Invoice not found
*/
type GetInvoiceByItemIDNotFound struct {
}

func (o *GetInvoiceByItemIDNotFound) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/invoices/byItemId/{itemId}][%d] getInvoiceByItemIdNotFound ", 404)
}

func (o *GetInvoiceByItemIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
