// Code generated by go-swagger; DO NOT EDIT.

package invoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ModifyInvoiceCustomFieldsReader is a Reader for the ModifyInvoiceCustomFields structure.
type ModifyInvoiceCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyInvoiceCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewModifyInvoiceCustomFieldsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewModifyInvoiceCustomFieldsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewModifyInvoiceCustomFieldsNoContent creates a ModifyInvoiceCustomFieldsNoContent with default headers values
func NewModifyInvoiceCustomFieldsNoContent() *ModifyInvoiceCustomFieldsNoContent {
	return &ModifyInvoiceCustomFieldsNoContent{}
}

/* ModifyInvoiceCustomFieldsNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type ModifyInvoiceCustomFieldsNoContent struct {
}

func (o *ModifyInvoiceCustomFieldsNoContent) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoices/{invoiceId}/customFields][%d] modifyInvoiceCustomFieldsNoContent ", 204)
}

func (o *ModifyInvoiceCustomFieldsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewModifyInvoiceCustomFieldsBadRequest creates a ModifyInvoiceCustomFieldsBadRequest with default headers values
func NewModifyInvoiceCustomFieldsBadRequest() *ModifyInvoiceCustomFieldsBadRequest {
	return &ModifyInvoiceCustomFieldsBadRequest{}
}

/* ModifyInvoiceCustomFieldsBadRequest describes a response with status code 400, with default header values.

Invalid invoice id supplied
*/
type ModifyInvoiceCustomFieldsBadRequest struct {
}

func (o *ModifyInvoiceCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoices/{invoiceId}/customFields][%d] modifyInvoiceCustomFieldsBadRequest ", 400)
}

func (o *ModifyInvoiceCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
