// Code generated by go-swagger; DO NOT EDIT.

package payment_transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/killbill/kbcli/v2/kbmodel"
)

// NotifyStateChangedReader is a Reader for the NotifyStateChanged structure.
type NotifyStateChangedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotifyStateChangedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNotifyStateChangedCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNotifyStateChangedBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewNotifyStateChangedNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNotifyStateChangedCreated creates a NotifyStateChangedCreated with default headers values
func NewNotifyStateChangedCreated() *NotifyStateChangedCreated {
	return &NotifyStateChangedCreated{}
}

/* NotifyStateChangedCreated describes a response with status code 201, with default header values.

Successfully notifiy state change
*/
type NotifyStateChangedCreated struct {
	Payload *kbmodel.Payment
}

func (o *NotifyStateChangedCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/paymentTransactions/{transactionId}][%d] notifyStateChangedCreated  %+v", 201, o.Payload)
}
func (o *NotifyStateChangedCreated) GetPayload() *kbmodel.Payment {
	return o.Payload
}

func (o *NotifyStateChangedCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.Payment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotifyStateChangedBadRequest creates a NotifyStateChangedBadRequest with default headers values
func NewNotifyStateChangedBadRequest() *NotifyStateChangedBadRequest {
	return &NotifyStateChangedBadRequest{}
}

/* NotifyStateChangedBadRequest describes a response with status code 400, with default header values.

Invalid paymentId supplied
*/
type NotifyStateChangedBadRequest struct {
}

func (o *NotifyStateChangedBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/paymentTransactions/{transactionId}][%d] notifyStateChangedBadRequest ", 400)
}

func (o *NotifyStateChangedBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNotifyStateChangedNotFound creates a NotifyStateChangedNotFound with default headers values
func NewNotifyStateChangedNotFound() *NotifyStateChangedNotFound {
	return &NotifyStateChangedNotFound{}
}

/* NotifyStateChangedNotFound describes a response with status code 404, with default header values.

Account or Payment not found
*/
type NotifyStateChangedNotFound struct {
}

func (o *NotifyStateChangedNotFound) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/paymentTransactions/{transactionId}][%d] notifyStateChangedNotFound ", 404)
}

func (o *NotifyStateChangedNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
