// Code generated by go-swagger; DO NOT EDIT.

package invoice_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/killbill/kbcli/v2/kbmodel"
)

// CreateChargebackReader is a Reader for the CreateChargeback structure.
type CreateChargebackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateChargebackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateChargebackCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateChargebackBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateChargebackNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateChargebackCreated creates a CreateChargebackCreated with default headers values
func NewCreateChargebackCreated() *CreateChargebackCreated {
	return &CreateChargebackCreated{}
}

/* CreateChargebackCreated describes a response with status code 201, with default header values.

Created chargeback successfully
*/
type CreateChargebackCreated struct {
	Payload *kbmodel.InvoicePayment
}

func (o *CreateChargebackCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoicePayments/{paymentId}/chargebacks][%d] createChargebackCreated  %+v", 201, o.Payload)
}
func (o *CreateChargebackCreated) GetPayload() *kbmodel.InvoicePayment {
	return o.Payload
}

func (o *CreateChargebackCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.InvoicePayment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateChargebackBadRequest creates a CreateChargebackBadRequest with default headers values
func NewCreateChargebackBadRequest() *CreateChargebackBadRequest {
	return &CreateChargebackBadRequest{}
}

/* CreateChargebackBadRequest describes a response with status code 400, with default header values.

Invalid payment id supplied
*/
type CreateChargebackBadRequest struct {
}

func (o *CreateChargebackBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoicePayments/{paymentId}/chargebacks][%d] createChargebackBadRequest ", 400)
}

func (o *CreateChargebackBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateChargebackNotFound creates a CreateChargebackNotFound with default headers values
func NewCreateChargebackNotFound() *CreateChargebackNotFound {
	return &CreateChargebackNotFound{}
}

/* CreateChargebackNotFound describes a response with status code 404, with default header values.

Account or payment not found
*/
type CreateChargebackNotFound struct {
}

func (o *CreateChargebackNotFound) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoicePayments/{paymentId}/chargebacks][%d] createChargebackNotFound ", 404)
}

func (o *CreateChargebackNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
