// Code generated by go-swagger; DO NOT EDIT.

package invoice_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CDNA-Technologies/kbcli/v3/kbmodel"
)

// GetInvoicePaymentReader is a Reader for the GetInvoicePayment structure.
type GetInvoicePaymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInvoicePaymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInvoicePaymentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInvoicePaymentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInvoicePaymentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetInvoicePaymentOK creates a GetInvoicePaymentOK with default headers values
func NewGetInvoicePaymentOK() *GetInvoicePaymentOK {
	return &GetInvoicePaymentOK{}
}

/* GetInvoicePaymentOK describes a response with status code 200, with default header values.

successful operation
*/
type GetInvoicePaymentOK struct {
	Payload *kbmodel.InvoicePayment
}

func (o *GetInvoicePaymentOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/invoicePayments/{paymentId}][%d] getInvoicePaymentOK  %+v", 200, o.Payload)
}
func (o *GetInvoicePaymentOK) GetPayload() *kbmodel.InvoicePayment {
	return o.Payload
}

func (o *GetInvoicePaymentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.InvoicePayment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoicePaymentBadRequest creates a GetInvoicePaymentBadRequest with default headers values
func NewGetInvoicePaymentBadRequest() *GetInvoicePaymentBadRequest {
	return &GetInvoicePaymentBadRequest{}
}

/* GetInvoicePaymentBadRequest describes a response with status code 400, with default header values.

Invalid payment id supplied
*/
type GetInvoicePaymentBadRequest struct {
}

func (o *GetInvoicePaymentBadRequest) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/invoicePayments/{paymentId}][%d] getInvoicePaymentBadRequest ", 400)
}

func (o *GetInvoicePaymentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInvoicePaymentNotFound creates a GetInvoicePaymentNotFound with default headers values
func NewGetInvoicePaymentNotFound() *GetInvoicePaymentNotFound {
	return &GetInvoicePaymentNotFound{}
}

/* GetInvoicePaymentNotFound describes a response with status code 404, with default header values.

Payment not found
*/
type GetInvoicePaymentNotFound struct {
}

func (o *GetInvoicePaymentNotFound) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/invoicePayments/{paymentId}][%d] getInvoicePaymentNotFound ", 404)
}

func (o *GetInvoicePaymentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
